name: GeminiHelper
version: '1.0-SNAPSHOT'
main: com.conquister.geminiHelper.GeminiHelper
api-version: '1.21'
description: Um plugin que fornece ajuda aos jogadores através da API do Gemini com informações específicas do servidor
folia-supported: true
softdepend: [PlaceholderAPI]

commands:
  ajuda:
    description: Consulta o assistente AI do servidor
    usage: /ajuda <pergunta>
    permission: geminihelper.use
  help:
    description: Consulta o assistente AI do servidor
    usage: /help <pergunta>
    permission: geminihelper.use
  gpt:
    description: Consulta o assistente AI do servidor
    usage: /gpt <pergunta>
    permission: geminihelper.use
  reloadconfig:
    description: Recarrega as configurações do plugin
    usage: /reloadconfig
    permission: geminihelper.admin

permissions:
  geminihelper.use:
    description: Permite usar o assistente AI
    default: true
  geminihelper.admin:
    description: Permite recarregar as configurações do plugin
    default: op